### ISSUE TITLE
[BUG]: dellemc.openmanage.idrac_system_info fails on iDRAC10 / 17G (SystemBoardCPUUsage)

### ISSUE THREAD

**Issue by xocoru** [dell/dellemc-openmanage-ansible-modules#1039]
### Bug Description

My playbook fails when I get information from one of the hosts with iDRAC 10
It says there is no URL:
"/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardCPUUsage"

### Component or Module Name

idrac_system_info

### Ansible Version

Ansible 2.19.2

### Python Version

Python 3.12.3

### iDRAC/OME/OME-M version

BIOS Version | 1.2.6
Device Type 17G Monolithic
Hardware Version 0.01
Firmware Version 1.20.25.00

### Operating System

MacOS 15.7

### Playbook Used

```
    - name: Collection System Information from IDRAC
      delegate_to: localhost
      dellemc.openmanage.idrac_system_info:
        idrac_ip: "{{ ansible_host }}"
        idrac_user: "{{ idrac_username }}"
        idrac_password: "{{ idrac_password }}"
        ca_path: "{{ cert_path }}"
        validate_certs: false
        timeout: 300
      register: system_info_fresh
      when: system_info is not defined
      tags:
        - facts
```

### Logs

```
[ERROR]: Task failed: Module failed: HTTP Error 404: Not Found
Origin: /Users/user/Git/asset-automations/playbooks/idrac_devices.yml:162:7

160         - opm
161
162     - name: Collection System Information from IDRAC
          ^ column 7

fatal: [server-xxxx.local -> localhost]: FAILED! => {
    "changed": false,
    "error_info": {
        "error": {
            "@Message.ExtendedInfo": [
                {
                    "Message": "The resource at the URI '/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardCPUUsage' was not found.",
                    "MessageArgs": [
                        "/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardCPUUsage"
                    ],
                    "MessageId": "Base.1.18.ResourceMissingAtURI",
                    "RelatedProperties": [],
                    "Resolution": "Place a valid resource at the URI or correct the URI and resubmit the request.",
                    "Severity": "Critical"
                },
                {
                    "Message": "Unable to complete the operation because the resource /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardCPUUsage entered is not found.",
                    "MessageArgs": [
                        "/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardCPUUsage"
                    ],
                    "MessageId": "IDRAC.2.11.SYS403",
                    "RelatedProperties": [],
                    "Resolution": "Enter the correct resource and retry the operation. For resources with numeric ID in the URI, enable the \"Redfish.1#NumericDynamicSegmentsEnable\" attribute and retry the operation. For information about valid resource, see the Redfish Users Guide available on the support site.",
                    "Severity": "Critical"
                }
            ],
            "code": "Base.1.18.GeneralError",
            "message": "A general error has occurred.  See Resolution for information on how to resolve the error, or @Message.ExtendedInfo if Resolution is not provided."
        }
    },
    "invocation": {
        "module_args": {
            "ca_path": "/Users/user/Git/asset-automations/certs/ca-bundle.pem",
            "idrac_ip": "10.1.1.1",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "root",
            "timeout": 300,
            "validate_certs": false
        }
    },
    "msg": "HTTP Error 404: Not Found"
}

```

### Steps to Reproduce

Just trying to get device information from iDRAC 10

### Expected Behavior

Got system_info

### Actual Behavior

Got the error about "HTTP Error 404: Not Found". I have checked the upper URI "/redfish/v1/Chassis/System.Embedded.1/Sensors"

and there is no SystemBoardCPUUsage branch:
```
{
    "Description": "Collection of Sensors",
    "Members": [
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PSU.Slot.1_MaximumFrequency"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PSU.Slot.1_InputPower"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan5_2"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PSU.Slot.2_MaximumFrequency"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan4_2"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PS1Current1"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan5_1"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU1VCCD1VR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan3_1"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PS2Current2"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU0Temp"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan4_1"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU0VCCINFVR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU1VCCINVR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PS2Voltage"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU1VCCINFVR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU0VCCD1VR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PSU.Slot.2_OutputPower"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PowerHeadroom"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan2_2"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardExhaustTemp"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PSU.Slot.1_OutputPower"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan6_2"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PSU.Slot.2_InputPower"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU1VCCD0VR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan3_2"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan6_1"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/PS1Voltage"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Temperature.DIMM_MAX"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU1Temp"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardCurrentConsumption"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardPwrConsumption"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan2_1"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan1_1"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/Fan1_2"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU0VCCINVR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU1VCCFAVR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU0VCCFAVR"
        },
        {
            "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors/CPU0VCCD0VR"
        }
    ],
    "Members@odata.count": 40,
    "Name": "SensorCollection",
    "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Sensors",
    "@odata.etag": "\"W/'gen-1'\"",
    "@odata.context": "/redfish/v1/$metadata#SensorCollection.SensorCollection",
    "@odata.type": "#SensorCollection.SensorCollection"
}
```

**Comment by xocoru** [comment]
Looks like these URLs are hardcoded 
in ansible_collections/dellemc/openmanage/plugins/module_utils/idrac_utils/info/system_board_metrics.py

`GET_SYSTEMBOARD_CPUUSAGE_URI_10 = "/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardCPUUsage"
`

And it looks like that non-200 response should be okay, just return {}, {}, {}, {}, {}, {}, {}, {}, {}, {}. 

```
    def get_cpu_usage_details(self):
        response = self.idrac.invoke_request(method='GET', uri=GET_SYSTEMBOARD_CPUUSAGE_URI_10)
        if response.status_code == 200:
            cpu_usage_avg_hour = response.json_data.get("Oem", {}).get("Dell", {}).get("AverageReadings", {}).get("LastHour", {}).get("Reading", NA)
            cpu_usage_avg_day = response.json_data.get("Oem", {}).get("Dell", {}).get("AverageReadings", {}).get("LastDay", {}).get("Reading", NA)
            cpu_usage_avg_week = response.json_data.get("Oem", {}).get("Dell", {}).get("AverageReadings", {}).get("LastWeek", {}).get("Reading", NA)
            cpu_usage_max_hour = response.json_data.get("Oem", {}).get("Dell", {}).get("PeakReadings", {}).get("LastHour", {}).get("Reading", NA)
            cpu_usage_max_day = response.json_data.get("Oem", {}).get("Dell", {}).get("PeakReadings", {}).get("LastDay", {}).get("Reading", NA)
            cpu_usage_max_week = response.json_data.get("Oem", {}).get("Dell", {}).get("PeakReadings", {}).get("LastWeek", {}).get("Reading", NA)
            cpu_usage_min_hour = response.json_data.get("Oem", {}).get("Dell", {}).get("LowestReadings", {}).get("LastHour", {}).get("Reading", NA)
            cpu_usage_min_day = response.json_data.get("Oem", {}).get("Dell", {}).get("LowestReadings", {}).get("LastDay", {}).get("Reading", NA)
            cpu_usage_min_week = response.json_data.get("Oem", {}).get("Dell", {}).get("LowestReadings", {}).get("LastWeek", {}).get("Reading", NA)
            cpu_usage_peak = response.json_data.get("PeakReading", NA)
            return (
                cpu_usage_avg_hour, cpu_usage_avg_day, cpu_usage_avg_week,
                cpu_usage_max_hour, cpu_usage_max_day, cpu_usage_max_week,
                cpu_usage_min_hour, cpu_usage_min_day, cpu_usage_min_week,
                cpu_usage_peak
            )
        return {}, {}, {}, {}, {}, {}, {}, {}, {}, {}

```

But invoke_request raises an exception ...

**Comment by rounak-adhikary** [comment]
@xocoru this has been fixed as a similar thing was reported in https://github.com/dell/dellemc-openmanage-ansible-modules/issues/1017
The fix has not been released yet though.

**Comment by rounak-adhikary** [comment]
The fix is targetted to be released by end of this month.

**Comment by xocoru** [comment]
I noticed that this issue relates to IDRAC behaviour. If the "Performance" tab is blank, you will not receive data via RedFish either.  
<img width="1466" height="641" alt="Image" src="https://github.com/user-attachments/assets/ca3d024e-fabb-49b4-ac2a-a18e53c0f6d0" />

I have opened the Service Ticket

**Comment by gokul-srivathsan** [comment]
@xocoru , since v10.0.1 and we have the issue #1017 has been closed, closing this issue. Please revert for queries, concerns, if any.

**Comment by nirousseau** [comment]
@gokul-srivathsan i am still experiencing the same issue iDRAC10 : (R470, firmware version: 1.20.80.00)

with latest published openmanage ansible :

```
Installing 'dellemc.openmanage:10.0.1' to '/home/ansible/.ansible/collections/ansible_collections/dellemc/openmanage'
dellemc.openmanage:10.0.1 was installed successfully
```

```
fatal: [p02.idrac.mt.lan -> localhost]: FAILED! =>
    changed: false
    error_info:
        error:
            '@Message.ExtendedInfo':
            -   Message: The resource at the URI '/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp'
                    was not found.
                MessageArgs:
                - /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                MessageId: Base.1.18.ResourceMissingAtURI
                RelatedProperties: []
                Resolution: Place a valid resource at the URI or correct the URI and resubmit
                    the request.
                Severity: Critical
            -   Message: Unable to complete the operation because the resource /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                    entered is not found.
                MessageArgs:
                - /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                MessageId: IDRAC.2.15.SYS403
                RelatedProperties: []
                Resolution: Enter the correct resource and retry the operation. For resources
                    with numeric ID in the URI, enable the "Redfish.1#NumericDynamicSegmentsEnable"
                    attribute and retry the operation. For information about valid resource,
                    see the Redfish Users Guide available on the support site.
                Severity: Critical
            code: Base.1.18.GeneralError
            message: A general error has occurred.  See Resolution for information on
                how to resolve the error, or @Message.ExtendedInfo if Resolution is not
                provided.
    msg: 'HTTP Error 404: Not Found'
...ignoring
fatal: [p01.idrac.mt.lan -> localhost]: FAILED! =>
    changed: false
    error_info:
        error:
            '@Message.ExtendedInfo':
            -   Message: The resource at the URI '/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp'
                    was not found.
                MessageArgs:
                - /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                MessageId: Base.1.18.ResourceMissingAtURI
                RelatedProperties: []
                Resolution: Place a valid resource at the URI or correct the URI and resubmit
                    the request.
                Severity: Critical
            -   Message: Unable to complete the operation because the resource /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                    entered is not found.
                MessageArgs:
                - /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                MessageId: IDRAC.2.15.SYS403
                RelatedProperties: []
                Resolution: Enter the correct resource and retry the operation. For resources
                    with numeric ID in the URI, enable the "Redfish.1#NumericDynamicSegmentsEnable"
                    attribute and retry the operation. For information about valid resource,
                    see the Redfish Users Guide available on the support site.
                Severity: Critical
            code: Base.1.18.GeneralError
            message: A general error has occurred.  See Resolution for information on
                how to resolve the error, or @Message.ExtendedInfo if Resolution is not
                provided.
    msg: 'HTTP Error 404: Not Found'
...ignoring
fatal: [p03.idrac.mt.lan -> localhost]: FAILED! =>
    changed: false
    error_info:
        error:
            '@Message.ExtendedInfo':
            -   Message: The resource at the URI '/redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp'
                    was not found.
                MessageArgs:
                - /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                MessageId: Base.1.18.ResourceMissingAtURI
                RelatedProperties: []
                Resolution: Place a valid resource at the URI or correct the URI and resubmit
                    the request.
                Severity: Critical
            -   Message: Unable to complete the operation because the resource /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                    entered is not found.
                MessageArgs:
                - /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp
                MessageId: IDRAC.2.15.SYS403
                RelatedProperties: []
                Resolution: Enter the correct resource and retry the operation. For resources
                    with numeric ID in the URI, enable the "Redfish.1#NumericDynamicSegmentsEnable"
                    attribute and retry the operation. For information about valid resource,
                    see the Redfish Users Guide available on the support site.
                Severity: Critical
            code: Base.1.18.GeneralError
            message: A general error has occurred.  See Resolution for information on
                how to resolve the error, or @Message.ExtendedInfo if Resolution is not
                provided.
    msg: 'HTTP Error 404: Not Found'
...ignoring

```

playbook.yaml
```
---
- name: "[METAL] REPORTING PLAYBOOK"
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: "Authenticate with BMC"
      delegate_to: localhost
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/redfish/v1/Systems"
        user: "{{ ipmi_user }}"
        password: "{{ ipmi_password }}"
        force_basic_auth: true
        validate_certs: false
        status_code: [200]

    - name: "[DELLEMC] Get system inventory"
      delegate_to: localhost
      when: "hardware_manufacturer == 'dellemc'"
      dellemc.openmanage.idrac_system_info:
        idrac_ip: "{{ ansible_host }}"
        idrac_user: "{{ ipmi_user }}"
        idrac_password: "{{ ipmi_password }}"
        validate_certs: false
```

**Comment by rounak-adhikary** [comment]
@nirousseau What you are facing is the issue raised in https://github.com/dell/dellemc-openmanage-ansible-modules/issues/1053.
Its fixed on the main branch.

**Comment by nirousseau** [comment]
> [@nirousseau](https://github.com/nirousseau) What you are facing is the issue raised in [#1053](https://github.com/dell/dellemc-openmanage-ansible-modules/issues/1053). Its fixed on the main branch.

Despite the fix, I have 404 not found error on " /redfish/v1/Chassis/System.Embedded.1/Sensors/SystemBoardInletTemp" endpoint, see my log above.

**Comment by nirousseau** [comment]
> > [@nirousseau](https://github.com/nirousseau) What you are facing is the issue raised in [#1053](https://github.com/dell/dellemc-openmanage-ansible-modules/issues/1053). Its fixed on the main branch.

EDIT : Alright, my bad, the fix has been included in October on master, but the current published role is from September. Sorry !
